# Copyright (c) LieberLieber Software GmbH
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: LemonTree.Automation Consistency Check

on:
 push:

env:
  ModelName: DemoModel
  ModelExtension: eapx
  LemonTreeAutomationExecutable: C:\Program Files\LieberLieber\LemonTree.Automation\LemonTree.Automation.exe

jobs:
  ConsistencyCheck:
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      # download Lemontree.Automation on a runner and setup the license
      - uses: LieberLieber/setup-LemonTree.Automation@v1
        id: GetLTA
        with:
          License: ${{secrets.LTALICENSE}} 
      #ExeLocation &"${{steps.GetLTA.outputs.LemonTreeAutomationExecutable}}"
                      
      - name: ConsistencyCheck
        run: |
          &"${{steps.GetLTA.outputs.LemonTreeAutomationExecutable}}" ConsistencyCheck --Model ${{env.ModelName}}.${{env.ModelExtension}}
 
     
    
